name: 'macOS'

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: macos-latest
    steps:
    - run: npm ci
    - run: npm run build
    - uses: actions/checkout@master
    - uses: ./ # Should show error messages
    