name: "Test setup-ruby itself"
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set the latest Ruby 2.6
      run: |
        echo "2.6.5" > .ruby-version

    - name: Set up the latest Ruby 2.6
      uses: masa-iwasaki/setup-rbenv@2ab0225
