on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
    - run: |
        export RBENV_ROOT=/usr/local/rbenv    
        export PATH="$RBENV_ROOT/bin:$PATH"
        eval "$(rbenv init -)"
        rbenv install 2.5.7
    